### ISSUE TITLE
!event create broken

### ISSUE THREAD

**Issue by TurbulentQuasarPhenotype** [TurbulentQuasarPhenotype/KrigsBot#1]
### Issue ###

Invoking "!event create 2021-03-20 12:00" does not result in the creation of an event.
The bot fails without any feedback to the caller.

### Logs ###
The following is written to journald from the KrigsBot service:

Mar 14 11:21:32 LXCNAME python3[5637]: Ignoring exception in command event create:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     ret = await coro(*args, **kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/home/KrigsBot/cogs/events.py", line 425, in create
Mar 14 11:21:32 LXCNAME python3[5637]:     with open(f"{EVENT_DIR}{id}.json", "w") as file:
Mar 14 11:21:32 LXCNAME python3[5637]: FileNotFoundError: [Errno 2] No such file or directory: './Events/2021-03-20#8962.json'
Mar 14 11:21:32 LXCNAME python3[5637]: The above exception was the direct cause of the following exception:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 903, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.command.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 1329, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.invoked_subcommand.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 859, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await injected(*ctx.args, **ctx.kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     raise CommandInvokeError(exc) from exc
Mar 14 11:21:32 LXCNAME python3[5637]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: './Eve
Mar 14 11:21:32 LXCNAME python3[5637]: Ignoring exception in command event create:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     ret = await coro(*args, **kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/home/KrigsBot/cogs/events.py", line 425, in create
Mar 14 11:21:32 LXCNAME python3[5637]:     with open(f"{EVENT_DIR}{id}.json", "w") as file:
Mar 14 11:21:32 LXCNAME python3[5637]: FileNotFoundError: [Errno 2] No such file or directory: './Events/2021-03-14#8400.json'
Mar 14 11:21:32 LXCNAME python3[5637]: The above exception was the direct cause of the following exception:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 903, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.command.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 1329, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.invoked_subcommand.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 859, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await injected(*ctx.args, **ctx.kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     raise CommandInvokeError(exc) from exc
Mar 14 11:21:32 LXCNAME python3[5637]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: './Eve
Mar 14 11:21:32 LXCNAME python3[5637]: Ignoring exception in command event create:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 903, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.command.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 1329, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.invoked_subcommand.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 851, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await self.prepare(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 786, in prepare
Mar 14 11:21:32 LXCNAME python3[5637]:     await self._parse_arguments(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 697, in _parse_arguments
Mar 14 11:21:32 LXCNAME python3[5637]:     transformed = await self.transform(ctx, param)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 542, in transform
Mar 14 11:21:32 LXCNAME python3[5637]:     raise MissingRequiredArgument(param)
Mar 14 11:21:32 LXCNAME python3[5637]: discord.ext.commands.errors.MissingRequiredArgument: date is a required argument that is missing.
Mar 14 11:21:32 LXCNAME python3[5637]: Ignoring exception in command event create:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     ret = await coro(*args, **kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/home/KrigsBot/cogs/events.py", line 425, in create
Mar 14 11:21:32 LXCNAME python3[5637]:     with open(f"{EVENT_DIR}{id}.json", "w") as file:
Mar 14 11:21:32 LXCNAME python3[5637]: FileNotFoundError: [Errno 2] No such file or directory: './Events/2021-03-20#8043.json'
Mar 14 11:21:32 LXCNAME python3[5637]: The above exception was the direct cause of the following exception:
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 903, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.command.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 1329, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await ctx.invoked_subcommand.invoke(ctx)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 859, in invoke
Mar 14 11:21:32 LXCNAME python3[5637]:     await injected(*ctx.args, **ctx.kwargs)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
Mar 14 11:21:32 LXCNAME python3[5637]:     raise CommandInvokeError(exc) from exc
Mar 14 11:21:32 LXCNAME python3[5637]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: './Eve
Mar 14 11:21:32 LXCNAME python3[5637]: KrigsBot has connected.
Mar 14 11:21:32 LXCNAME python3[5637]: Traceback (most recent call last):
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/home/KrigsBot/KrigsBot.py", line 58, in <module>
Mar 14 11:21:32 LXCNAME python3[5637]:     bot.run(TOKEN, reconnect=True)
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 680, in run
Mar 14 11:21:32 LXCNAME python3[5637]:     loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
Mar 14 11:21:32 LXCNAME python3[5637]:     self._check_closed()
Mar 14 11:21:32 LXCNAME python3[5637]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
Mar 14 11:21:32 LXCNAME python3[5637]:     raise RuntimeError('Event loop is closed')
Mar 14 11:21:32 LXCNAME python3[5637]: RuntimeError: Event loop is closed
Mar 14 11:21:33 LXCNAME systemd[1]: krigsbot.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 11:21:33 LXCNAME systemd[1]: krigsbot.service: Failed with result 'exit-code'.
Mar 14 11:21:33 LXCNAME systemd[1]: Stopped Krigssvinen Discord Bot.
Mar 14 11:21:33 LXCNAME systemd[1]: Started Krigssvinen Discord Bot.

**Comment by TurbulentQuasarPhenotype** [comment]
### Cause ###
Bug occurred due to systemd service not being set to the corrrect workingpath.

In the Event cog, the event directory is given by use of relative path, assuming it will be directly underneath whereever KrigsBot.py is running:
https://github.com/TurbulentQuasarPhenotype/KrigsBot/blob/a9b800af2d2fc1f0daf9b0412ceb88ba7ac4483d/cogs/events.py#L19

### Fixed ###
Code is correct as written; the issue was the systemd service created to run the bot.
> Added "WorkingDirectory=/home/KrigsBot/" to krigsbot.service to correct the running directory.
